import type { GetServerSideProps, NextPage } from "next";
import Head from "next/head";
import React, { useRef } from "react";
import BlogItem from "../../components/BlogItem";
import PageTitle from "../../components/PageTitle";
import { BlogType } from "../../interfaces/interfaces";
import { useRouter } from "next/router";

interface Props {
  blogData: BlogType[];
}

const Blog: NextPage<Props> = ({ blogData }) => {
  const router = useRouter();

  const searchRef = useRef<HTMLInputElement>(null);

  return (
    <>
      <Head>
        <title>Store - Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title="Blog" />

      <section className="bg0 p-t-62 p-b-60">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                {blogData.length < 1 ? (
                  <p>
                    There are no results for your search.. Please enter a more
                    specific value.
                  </p>
                ) : (
                  blogData.map((blog) => {
                    return <BlogItem key={blog.id} {...blog} />;
                  })
                )}
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <form className="bor17 of-hidden pos-relative">
                  <input
                    className="stext-103 cl2 plh4 size-116 p-l-28 p-r-55"
                    type="text"
                    name="search"
                    placeholder="Search"
                    ref={searchRef}
                    onChange={() => {
                      {
                        searchRef.current?.value === ""
                          ? router.push({
                              pathname: "/blog",
                            })
                          : router.push({
                              pathname: "/blog",
                              query: {
                                ...router.query,
                                q: searchRef.current?.value,
                              },
                            });
                      }
                    }}
                  />

                  <button className="flex-c-m size-122 ab-t-r fs-18 cl4 hov-cl1 trans-04">
                    <i className="zmdi zmdi-search"></i>
                  </button>
                </form>

                <div className="p-t-55">
                  <h4 className="mtext-112 cl2 p-b-33">Categories</h4>

                  <ul>
                    <li className="bor18">
                      <button
                        className={`${
                          router.query.category === "fashion"
                            ? "how-active1"
                            : ""
                        } dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4`}
                        onClick={() => {
                          router.push({
                            pathname: "/blog",
                            query: {
                              ...router.query,
                              category: "fashion",
                            },
                          });
                        }}>
                        Fashion
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className={`${
                          router.query.category === "beauty"
                            ? "how-active1"
                            : ""
                        } dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4`}
                        onClick={() => {
                          router.push({
                            pathname: "/blog",
                            query: {
                              ...router.query,
                              category: "beauty",
                            },
                          });
                        }}>
                        Beauty
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className={`${
                          router.query.category === "streetstyle"
                            ? "how-active1"
                            : ""
                        } dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4`}
                        onClick={() => {
                          router.push({
                            pathname: "/blog",
                            query: {
                              ...router.query,
                              category: "streetstyle",
                            },
                          });
                        }}>
                        Street Style
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className={`${
                          router.query.category === "lifestyle"
                            ? "how-active1"
                            : ""
                        } dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4`}
                        onClick={() => {
                          router.push({
                            pathname: "/blog",
                            query: {
                              ...router.query,
                              category: "lifestyle",
                            },
                          });
                        }}>
                        Life Style
                      </button>
                    </li>

                    <li className="bor18">
                      <button
                        className={`${
                          router.query.category === "diy" ? "how-active1" : ""
                        } dis-block stext-115 cl6 hov-cl1 trans-04 p-tb-8 p-lr-4`}
                        onClick={() => {
                          router.push({
                            pathname: "/blog",
                            query: {
                              ...router.query,
                              category: "diy",
                            },
                          });
                        }}>
                        DIY & Crafts
                      </button>
                    </li>
                  </ul>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default Blog;

export const getServerSideProps: GetServerSideProps = async ({ query }) => {
  let blogRes: Response;

  if (query.category && query.q) {
    blogRes = await fetch(
      `http://localhost:5001/blogs?category_like=${query.category}&q=${query.q}`
    );
  } else if (query.category) {
    blogRes = await fetch(
      `http://localhost:5001/blogs?category_like=${query.category}`
    );
  } else if (query.q) {
    blogRes = await fetch(`http://localhost:5001/blogs?q=${query.q}`);
  } else {
    blogRes = await fetch(`http://localhost:5001/blogs`);
  }

  const blogData: BlogType[] = await blogRes.json();

  return {
    props: { blogData },
  };
};
