import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import CategoryPicker from "../components/CategoryPicker";
import FeaturedBlogs from "../components/FeaturedBlogs";
import FeaturedProducts from "../components/FeaturedProducts";
import {
  BannerContentType,
  BlogType,
  ProductType,
} from "../interfaces/interfaces";

interface Props {
  bannerContentData: BannerContentType;
  productArrData: ProductType[];
  blogArrData: BlogType[];
}

const Home: NextPage<Props> = ({
  bannerContentData,
  productArrData,
  blogArrData,
}) => {
  return (
    <>
      <Head>
        <title>Store</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Banner
        preTitle={bannerContentData.preTitle}
        title={bannerContentData.title}
      />

      <CategoryPicker />

      <FeaturedProducts arr={productArrData} />

      <FeaturedBlogs arr={blogArrData} />
    </>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  const bannerContentRes = await fetch(`http://localhost:5001/banner_content`);
  const bannerContentData: BannerContentType = await bannerContentRes.json();

  const productArrRes = await fetch(`http://localhost:5001/products/?_limit=4`);
  const productArrData: ProductType[] = await productArrRes.json();

  const blogArrRes = await fetch(`http://localhost:5001/blogs/?_limit=3`);
  const blogArrData: BlogType[] = await blogArrRes.json();

  return {
    props: {
      bannerContentData,
      productArrData,
      blogArrData,
    },
  };
};
