import type { GetStaticPaths, GetStaticProps, NextPage } from "next";
import Head from "next/head";
import PageTitle from "../../../components/PageTitle";
import RelatedBlogs from "../../../components/RelatedBlogs";
import { BlogType } from "../../../interfaces/interfaces";
import { randomNumber } from "../../../utils/utils";

interface Props {
  blogData: BlogType;
  relatedBlogsData: BlogType[];
}

const BlogDetail: NextPage<Props> = ({ blogData, relatedBlogsData }) => {
  return (
    <>
      <Head>
        <title>Store - title</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PageTitle title={blogData.title} />

      <section className="bg0 p-t-52 p-b-20">
        <div className="container">
          <div className="row">
            <div className="col-md-8 col-lg-9 p-b-80">
              <div className="p-r-45 p-r-0-lg">
                <div className="wrap-pic-w how-pos5-parent">
                  <img src={blogData.img} alt="IMG-BLOG" />
                </div>

                <div className="p-t-32">
                  <span className="flex-w align-items-center flex-m stext-111 cl2 p-b-19">
                    <span className="flex-c-m mr-3 bor7 p-lr-15 trans-04">
                      {blogData.category}
                    </span>

                    <span>
                      <span className="cl4">By</span> {blogData.author}
                      <span className="cl12 m-l-4 m-r-6">|</span>
                    </span>

                    <span>{blogData.date}</span>
                  </span>

                  <h4 className="ltext-109 cl2 p-b-28">{blogData.title}</h4>

                  <p className="stext-117 cl6 p-b-26">
                    {blogData.first_content}
                  </p>

                  <p className="stext-117 cl6 p-b-26">
                    {blogData.second_content}
                  </p>
                </div>
              </div>
            </div>

            <div className="col-md-4 col-lg-3 p-b-80">
              <div className="side-menu">
                <RelatedBlogs arr={relatedBlogsData} />
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
};

export default BlogDetail;

export const getStaticPaths: GetStaticPaths = async () => {
  const allBlogsRes = await fetch(`http://localhost:5001/blogs`);
  const allBlogsData: BlogType[] = await allBlogsRes.json();

  const paths = allBlogsData.map((blog) => {
    return {
      params: {
        id: blog.id,
      },
    };
  });

  return {
    paths,
    fallback: false,
  };
};

export const getStaticProps: GetStaticProps = async ({ params }) => {
  let blogData: BlogType | undefined = undefined;

  const getRandomNumber = randomNumber(0, 6).toString();

  const relatedBlogsRes = await fetch(
    `http://localhost:5001/blogs?_start=${getRandomNumber}&_limit=3`
  );
  const relatedBlogsData: BlogType[] = await relatedBlogsRes.json();

  if (params?.id) {
    const blogRes = await fetch(`http://localhost:5001/blogs/${params.id}`);
    blogData = await blogRes.json();
  }
  return {
    props: { blogData, relatedBlogsData },
  };
};
